### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by tekknolagi** [mikhailvs/torrent-ruby#2]
I can't figure out how to `require` this gem after installing it.

`require torrent_ruby`, `require torrent-ruby`, and others don't work.

What should I be `require`-ing?

**Comment by murtali** [comment]
Having similar issue. Tried using Ruby 1.9.1 with no luck.

**Comment by tekknolagi** [comment]
Any luck?

**Comment by tekknolagi** [comment]
yeah that's fair I haven't used Ruby in ~5 years

**Comment by mikhailvs** [comment]
Hah, I haven't even thought about this repo since 2012
